decode:
  latest:
    entrypoints:
      train:
        app:
          cmd: ["--config-dir=/data/config", "--config-name=config", "Paths.experiment=/output"]
          env: ["wandb_api_key"]
        handler:
          image_url: "public.ecr.aws/d2r7a3u1/decode:dev_multiphot_tar"
          aws_job_def: decode_train_latest
          files_down:
            config_id: config
            data_ids: data
          files_up: ["output"]
          aws_resources:
            hardware:
              MEMORY: 8000
              VCPU: 4
              GPU: 1
            timeout: 18000
